### ISSUE TITLE
Address changes after xarray_filters changes and Elm PR 187

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/earthio#28]
After these two are merged:
 *  [xarray_filters PR 8](https://github.com/ContinuumIO/xarray_filters/pull/8)
 * [elm PR 187](https://github.com/ContinuumIO/elm/pull/187)

For examples of nomenclature and more substantial changes to reshaping and ElmStore:
 * [reshape.py](https://github.com/ContinuumIO/earthio/blob/master/earthio/reshape.py) moved and changed
 * The usage of `flatten` -> to_features
 * `inverse_flatten` -> from_features
 * `ElmStore` -> `MLDataset`
 * Other changes

**Comment by PeterDSteinberg** [comment]
Another change associated with [xarray_filters PR 8](https://github.com/ContinuumIO/xarray_filters/pull/8):
 * Modify `load_array` and related functions to return `MLDataset` instances

**Comment by gbrener** [comment]
Closing this issue, since it seems to be finished, and the remaining item about `load_array` is being addressed here: https://github.com/ContinuumIO/earthio/issues/31
