### ISSUE TITLE
Test data downloader - GeoTiff decompression issue

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/earthio#4]
See if the data downloader script in ./scripts is having trouble decompressing GeoTiffs.  Fix that, if needed, then remove the workaround that is in .travis.yml (see the TODO notes near the bottom of .travis.yml).

**Comment by PeterDSteinberg** [comment]
The downloaded `tif.tar.bz2` appears quite small compared to other files:

```
psteinberg at 0178-psteinberg in ~/Documents/earth/earthio/scripts on update_name [?]
$ ls -lth
total 333216
-rw-r--r--    1 psteinberg  wheel    14M May  4 14:05 netcdf.tar.bz2
-rw-r--r--    1 psteinberg  wheel   1.4K May  4 14:05 tif.tar.bz2
-rw-r--r--    1 psteinberg  wheel   109M May  4 14:05 hdf5.tar.bz2
-rw-r--r--    1 psteinberg  wheel    39M May  4 14:04 hdf4.tar.bz2
-rwxr-xr-x    1 psteinberg  staff   4.9K May  4 07:13 download_test_data.py
```

Looking at the unpacking of that `tif.tar.bz2`, it is also unpacking tif files that are much too small:

```
psteinberg at 0178-psteinberg in ~/Documents/earth/earthio/scripts on update_name [?]
$ ls -lth tif/L8/015/033/LC80150332013207LGN00/LC80150332013207LGN00_B1.TIF
-rw-r--r--  1 psteinberg  staff   133B May  1 12:21 tif/L8/015/033/LC80150332013207LGN00/LC80150332013207LGN00_B1.TIF
```
Compared to the version from `elm-data`:
```
psteinberg at 0178-psteinberg in ~/Documents/earth/earthio/scripts on update_name [?]
$ ls -lth ../../elm-data/tif/L8/015/033/LC80150332013207LGN00/LC80150332013207LGN00_B1.TIF
-rw-r--r--  1 psteinberg  staff    63M Jul 15  2016 ../../elm-data/tif/L8/015/033/LC80150332013207LGN00/LC80150332013207LGN00_B1.TIF
```

I assigned this task to you @gbrener (it can wait until post-vacation - we have a workaround).

**Comment by gbrener** [comment]
Looking into it now. Thanks @PeterDSteinberg

**Comment by gbrener** [comment]
@PeterDSteinberg , looking into the issue, I believe this is due to `git-lfs` not being installed on my computer before cloning the repo. After installing it I successfully downloaded all the files and re-uploaded them.

**Comment by gbrener** [comment]
Verified; closing. Thanks
